[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
rust2go = { path = "../rust2go" }
monoio = { version = "0.2", features = ["sync"] }

[build-dependencies]
rust2go = { path = "../rust2go", features = ["gen"] }
