[package]
name = "rust2go"
version = "0.0.2"

description = "rust2go lib"

authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rust2go-macro = { version = "0.0.2", path = "../rust2go-macro" }

anyhow = "1"
bindgen = "0.69"

syn = { version = "2", features = ["full"], optional = true }
quote = { version = "1", optional = true }
proc-macro2 = { version = "1", optional = true }

[features]
default = ["gen"]
gen = ["syn", "quote", "proc-macro2"]
